### ISSUE TITLE
Blank page while trying to access the website

### ISSUE THREAD

**Issue by crazyuploader** [surajmandalcell/covid-tracker-India#1]
Firing up "https://surajmandalcell.github.io/covid-tracker-India/" doesn't do anything

![image](https://user-images.githubusercontent.com/49350241/78254511-a87fd600-7513-11ea-8c46-b791806c2a7f.png)

**Comment by surajmandalcell** [comment]
Wrong url oops 🤭, since I'm using netlify for publishing its hosted on netlify not on github pages.

Go to https://covid-19-india.netlify.com/   to access pwa
